# Generated by Django 4.2.5 on 2023-09-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='secret',
        ),
    ]
